### ISSUE TITLE
Set up page missing (not built yet?)

### ISSUE THREAD

**Issue by jenlampton** [civicrm/civicrm-backdrop#132]
Hello, I'm doing my best to follow the instructions on https://docs.civicrm.org/installation/en/latest/backdrop/ for how to add CiviCRM to an existing Backdrop site. My problem occurs on step 2, clicking the link to set up CiviCRM. The path `civicrm/setup` throws a 404 on my backdrop site.

I dug into the code for that page, and found that there wasn't any. the function `civicrm_setup_page()` doesn't seem to return HTML under any conditions (in one case it returns an empty string, and in the other it simply calls `exit();`).

Does this mean that the installer UI for Backdrop has not been built yet?

**Comment by MegaphoneJon** [comment]
It's been a while since I installed via the UI -  but I just went to `mysite.org/civicrm/setup` on a production Backdrop/Civi site and I got some text back.  I grepped and found it in `modules/civicrm/install/index.php` around line 1680.  Which tracks with my memory that traditionally the installer was its own PHP file (similar to Drupal).   `civicrm/setup` isn't in the table that powers the router/front controller, so I don't know how that redirect works.

If your goal is just to get it installed and move on, you might try `modules/civicrm/install/index.php` instead.

**Comment by jenlampton** [comment]
Thanks @MegaphoneJon I'll give that a try.

**Comment by jenlampton** [comment]
I also got a file-not-found on `modules/civicrm/install/index.php` and `modules/contrib/civicrm/install/index.php` so I deleted the archive I'd grabbed from the [CiviCRM download page](https://civicrm.org/download) and tried again. The second time the module unpacked fine, and I was able to load up `mysite.org/civicrm/setup` without an issue. IDK what happened to the first download, but I'm suspect this may have been a one-time problem (so, closing issue).

**Comment by herbdool** [comment]
@MegaphoneJon the new way to install is just enable the CiviCRM module on the modules page and it will then provide a link in the message for installing/configuring CiviCRM.

(@jenlampton or anyone else looking for help regarding a 404: if someone is setting up Backdrop and CiviCRM on Lando, the default web server setup will result in 404. There's a workaround: switch to using nginx in the .lando.yml instead of apache. I spent some time trying to fix it but stopped when I found the workaround.)
