### ISSUE TITLE
Include Backdrop in the official CiviCRM documentation and mention in the official website.

### ISSUE THREAD

**Issue by klonos** [civicrm/civicrm-backdrop#16]
This is a todo for when we are ready.

They mention for example for example that it can be installed in Drupal, Wordpress and Joomla. We should add Backdrop there (+ their [download section](https://civicrm.org/download/list) of course).

Pages/articles in civicrm.org that mention Drupal: https://www.google.com.au/search?q=drupal+site:civicrm.org

**Comment by PalanteJon** [comment]
Hi there - I've been working on this!

Josh Gowans (CiviCRM project manager) reached out last week to do joint PR for Backdrop/CiviCRM on the respective sites - but hasn't yet heard back from folks.  If you go to https://chat.civicrm.org, you can hit him up on the Mattermost install (username: @josh).

There was initially a desire to make CiviCRM for Backdrop "stable" with 4.7.9 (next week's release) but that's been shelved, both because of bugs and wanting to coordinate with Backdrop core folks.  There's still a desire (by Josh and myself) to see this happen with the August release if possible.

Also, I've started working on adding Backdrop to docs - starting with the Backdrop installation guide.  It's not done yet: https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Backdrop  Note that items 6 and higher still reference Drupal.

Unfortunately, while I was testing my instructions, I found a bug (CRM-19011) that, while minor, is something that almost any Backdrop install will experience.  I'm hoping to fix that later this week, then go back to updating docs.

**Comment by nganivet** [comment]
Jon,

There are in fact quite a few dos that are going to need updating:
- the User manual mentions Drupal quite a lot: 
https://docs.civicrm.org/user/en/stable/search.html?q=drupal. It is 
build with readthedocs and needs to be modified through: 
https://github.com/civicrm/civicrm-user-guide
- the Administrator guide is what you have identified. It is still in 
the wiki (but probably not for long)
- the Developers guide is in the wiki but in the process of being 
migrated to readthedocs at: https://github.com/civicrm/civicrm-dev-docs. 
I do not know where this migration is and whether we are supposed to 
update the wiki or the git repo at this point in time. @totten might 
know.

Excited to see the Backdrop port making progress. Thanks for your hard 
work.

--Nicolas.

------ Original Message ------

**Comment by klonos** [comment]
> ...wanting to coordinate with Backdrop core folks.

@quicksketch, @jenlampton ...something for our weekly dev meeting agenda this Thursday 😉

**Comment by herbdool** [comment]
oops, I've stepped on your toes @PalanteJon ! I had done a quick once over on a copy of the Drupal wiki page and linked it on the front: https://wiki.civicrm.org/confluence/display/CRMDOC/CiviCRM+Documentation https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Backdrop+CMS

Merge your version with this one or scrap mine?

**Comment by PalanteJon** [comment]
Herb - alternatively, I've stepped on yours!  I'll review and merge.  I didn't finish mine because as I was testing them I ran into CRM-29011.

**Comment by herbdool** [comment]
Alright, thanks! It still needs a bit of clean-up plus needs checking all the linked docs etc.

I tested CRM-29011 on my backdrop/civi test install and couldn't replicate. But I could do a fresh install and see.
