### ISSUE TITLE
Profile options still say "Drupal"

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-backdrop#83]
![Screen Shot 2019-06-13 at 12 10 14 PM](https://user-images.githubusercontent.com/871421/59452858-457e5080-8dd4-11e9-8555-7b3d26a47efb.jpg)

When adding/editing a profile, the checkbox options still say Drupal.

**Comment by MegaphoneJon** [comment]
@laryn I fixed this elsewhere - https://github.com/civicrm/civicrm-core/pull/14288.  Moreover, see @mlutfy's criticism, and my comments on https://github.com/civicrm/civicrm-core/pull/14286.  The correct way to handle this would be to create a method on the `CRM_Utils_System_*` classes that returns the name - and ideally a second method for the "User Permissions" URL - so these can all be fixed in a reliable way.

**Comment by laryn** [comment]
Thanks @MegaphoneJon! I also noticed that it's done slightly differently in the database integration section, using the generic "CMS" instead of the specific name of the CMS:

![Screen Shot 2019-06-18 at 9 53 06 AM](https://user-images.githubusercontent.com/871421/59694937-0161c600-91af-11e9-8f96-af9f50c0b20c.jpg)

I'm not sure if we need to standardize these for consistency or not.

**Comment by laryn** [comment]
Moved to https://lab.civicrm.org/dev/backdrop/-/issues/2 so closing this issue.
